# Generated by Django 5.0.3 on 2024-09-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbvapp", "0002_company_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
    ]
