# Generated by Django 5.1 on 2024-09-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cbvapp", "0003_alter_company_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="cars_img",
            field=models.ImageField(blank=True, null=True, upload_to="cars/"),
        ),
    ]
